### ISSUE TITLE
Feature request: Support for relative mouse movements - reopened

### ISSUE THREAD

**Issue by badda71** [ultravnc/UltraVNC#12]
Feature request https://github.com/ultravnc/UltraVNC/issues/1 is closed but has actually not been implemented by the latest release. Looking at the code, gii-protocol extension is implemented, but it is ONLY possible to add ONE input device in order to emulate a touch-screen (with 1-10 valuators for 1-10 touch points), not a mouse with relative movements.

**Comment by Neustradamus** [comment]
@RudiDeVos: Please look it?

**Comment by Neustradamus** [comment]
@RudiDeVos: Please look it?

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look?

**Comment by Neustradamus** [comment]
@badda71: What is the status with the latest version?

**Comment by Neustradamus** [comment]
@badda71: What is the status with the latest stable/dev build?
1.4.3.1: https://forum.uvnc.com/viewtopic.php?t=37831
1.4.3.3-dev: https://forum.uvnc.com/viewtopic.php?t=37855

**Comment by badda71** [comment]
Give me some time to check pls

**Comment by Neustradamus** [comment]
@badda71: Have you looked?

**Comment by badda71** [comment]
still need some time, I'll get to it

**Comment by Neustradamus** [comment]
@badda71: Have you looked with the latest version?
- https://forum.uvnc.com/

**Comment by Neustradamus** [comment]
@badda71: Have you looked with the latest version?
There is a 1.5.0.0-dev.

**Comment by Neustradamus** [comment]
@badda71: Any news? It can be closed?

**Comment by Neustradamus** [comment]
@badda71: Have you tested latest development version?
It has been solved?

**Comment by badda71** [comment]
No, sorry, not solved. Still, looking at the code, gii-protocol extension is implemented, but the client only creates ONE Gii input device on the server which is used for transfer of touch information (with 1-10 valuators for 1-10 touch points), not a mouse with relative movements.
E.g. in gii.h, you define the event mask of the input device (#define rfbGIIevMaskValuatorAbsolute 0x00002000) - as per the RFC protocol definition at https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst, this is "Valuator absolute", meaning only absolute valuator values are transferred. For a mouse with relative movements, I would expect the event mask to be 0x00000D00 (Pointer relative | Pointer button press | Pointer button release). Apart from this, a test with the current downloadable dev binaries confirms, that games, that expect relative mouse movements, are not working.
I would love to help with a PR, but spare time is currently an issue :-(

**Comment by RudiDeVos** [comment]
Same here, spare time is limited.
The gii  code was provided by a company to work with there CNC machines, i also need to study it and it need to do the same out of the box as it does now
