### ISSUE TITLE
why there's always a black icon under my cursor?

### ISSUE THREAD

**Issue by tp01-gogogo** [ultravnc/UltraVNC#129]
![image](https://github.com/ultravnc/UltraVNC/assets/111100869/82546983-321f-4d9b-875d-2f61c65a85c7)
I have tried all of the settings about mouse and failed.
version:1.4.3.6
server:win11 viewer:win10

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look?

**Comment by Neustradamus** [comment]
@tp01-gogogo: Can you try a recent UltraVNC version > 1.6?
Have you same problem?

**Comment by RudiDeVos** [comment]
Thanks for the info
Settings / Accessibility / Mouse pointer and touch / Mouse pointer style

**Comment by RudiDeVos** [comment]
Accessibility enlarged cusor show a black rectangle
Found, git updated, Fixed in next update

**Comment by Neustradamus** [comment]
@tp01-gogogo, @mikemeinz: Can you try the 1.7.1.1-dev release build?
- https://uvnc.eu/download/1710/UltraVNC_1711_x86_Setup.exe
- https://uvnc.eu/download/1710/UltraVNC_1711_x64_Setup.exe
- https://uvnc.eu/download/1710/UltraVNC_1711-dev.zip

Can you confirm the fix?

**Comment by mikemeinz** [comment]
Installed 1.7.1.1-dev on X64 Server. Restarted PC.
Installed 1.7.1.1-dev on X64 Client.

Connect to server and still see black box around the cursor.

**Comment by Neustradamus** [comment]
@RudiDeVos: @mikemeinz has done a test, can you look again?

**Comment by mikemeinz** [comment]
This is what it looks like:

<img width="60" height="55" alt="Image" src="https://github.com/user-attachments/assets/aae8dd70-b457-404b-9eba-74dc90188baa" />

**Comment by RudiDeVos** [comment]
On my viewer it looks ,like

<img width="813" height="403" alt="Image" src="https://github.com/user-attachments/assets/949b1911-1be1-4793-87e6-d1a84831ad9d" />

haha it seems to give a blackbox only when the cursor is not enlarged

**Comment by mikemeinz** [comment]
In my experience size made no difference. Default or enlarged results in the same behavior.

When I move the cursor using the server mouse, the cursor on the client that moves has no black box.
When I move the cursor using the client mouse, the cursor on the client has the black box.

Let me know, if you want me to run a debug-version to collect log information for you.

**Comment by RudiDeVos** [comment]
Only change in 1712 color cursor handling
i fast tested small/lage b&w and color cursors (server handling and let client deal with cursor), this are 2 different methods in code
https://uvnc.eu/download/1710/UltraVNC_1712_x86_Setup.exe
https://uvnc.eu/download/1710/UltraVNC_1712_x64_Setup.exe

**Comment by mikemeinz** [comment]
Installed X64 on Server PC. Restarted Server PC.
Installed X64 on Client PC.

Started viewer and connected to server.

No black box!!!

Thank you!!!

**Comment by Neustradamus** [comment]
Good news about recent @RudiDeVos changes and the 1.7.1.2-dev release build and the very fast @mikemeinz test :)
If all tickets will be like it!

**Comment by mikemeinz** [comment]
I downloaded X64 version and installed on **the client** PC. Test OK, Attached is image of my enlarged cursor. Note the smaller cursor within the larger cursor. That doesn't bother me. I just wanted you to know about it in case it concerns you, 

Do I need to install on the server PC to do a more thorough test?

<img width="84" height="79" alt="Image" src="https://github.com/user-attachments/assets/3e3c7a9b-e660-4955-90e3-703975155aff" />

**Comment by mikemeinz** [comment]
I updated the server today. Same results as four days ago.

Thanks

**Comment by Neustradamus** [comment]
@tp01-gogogo, @mikemeinz: At this time, can you try the 1.8.0.5 release build?
- https://uvnc.eu/download/1800/UltraVNC_1805_x64_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1805_x86_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1805.zip

Can you check the @jonathanpoelen remark here?
- https://github.com/ultravnc/UltraVNC/issues/336

What do you think?

**Comment by mikemeinz** [comment]
Installed 1.8.0.5 X64 on server and client.
Using standard colored cursor, size 2, mouse pointer trails, trails length=7,mouse pointer shadow on both client and server.

Attached is screen capture of the server cursor as seen on the client.

<img width="734" height="274" alt="Image" src="https://github.com/user-attachments/assets/0496a11f-5e92-442e-b082-8b38a20cc4ca" />

**Comment by Neustradamus** [comment]
@mikemeinz: Thanks for your test!

It has been updated in 2 sides?

I am not sure, it is good or not for you?

Size must be same in local machine and remote machine?

On your screenshot, why there is a blue mouse background?

There are options about cursor in UltraVNC Viewer -> Options -> Input.
Have you tried?

cc: @RudiDeVos.

---------------------

About mouse cursor, there are different tickets:

@jonathanpoelen has done a ticket:
- https://github.com/ultravnc/UltraVNC/issues/336

@chaihahaha has done a ticket:
- https://github.com/ultravnc/UltraVNC/issues/276

@oper1000 has done a ticket:
- https://github.com/ultravnc/UltraVNC/issues/110

**Comment by mikemeinz** [comment]
UltraVNC was updated on both client and server.
Blue background in cursor image because my desktop background color is blue.
I have cursor size set the same on client and server. I can test different sizes tomorrow. I will look at UltraVNC cursor options tomorrow, too.
My test today worked OK.

**Comment by Neustradamus** [comment]
@mikemeinz: Thanks for your answer :)
Yes, please test different options.

So the cursors have same options but the remote cursor is more big than local cursor?

**Comment by mikemeinz** [comment]
**Test 1**
Changed on client Windows Settings / Accessibility / Mouse pointer and touch so that the mouse pointer on client is size=5 and server size=2. When connected to server with UltraVNC, client mouse pointer is the size defined in server's Windows Settings / Accessibility / Mouse pointer and touch.  
**Results: OK - Mouse pointer on client is size as defined on  server.  Small pointer image appeared inside larger pointer image same as the image I sent previously with the blue background. **

**Test 2**
Changed Windows Settings / Accessibility / Mouse pointer and touch so that the mouse pointer on client is size=2 and on server size=2.  
**Results: OK but small mouse pointer image appeared inside larger pointer image; same as image I sent previously with the blue background.  **

**Test 3**
With Windows Settings / Accessibility / Mouse pointer and touch / size set the same, enabled Viewer / Options / Input / Let remote server deal with mouse pointer.
**Results: Small mouse pointer image appeared inside larger mouse pointer image as previous tests. Because the mouse pointer is managed by server, could not do screen shot on client. I would not use this option. Prefer default "Track remote cursor locally" option so I can do screen shot..** 

**NOTE**: The small mouse pointer arrow that appears within the larger mouse pointer arrow (see image I sent previosuly), does not display in the Mouse Pointer Trails when the cursor is moved. It only appears in the stationery cursor.

**Comment by oper1000** [comment]
so there is a new version that fixed this issus ?

**Comment by Neustradamus** [comment]
@mikemeinz: Thanks for your test!
Hope that @RudiDeVos can answer you about it.

@oper1000: Normally since several months but you have not done a feedback to confirm!

**Comment by RudiDeVos** [comment]
I'm working on the unicode FT,  not the cursor, nothing changed

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the comments?

What do you think about @mikemeinz feedback?
- https://github.com/ultravnc/UltraVNC/issues/129#issuecomment-4008716293
- https://github.com/ultravnc/UltraVNC/issues/129#issuecomment-4232858092
- https://github.com/ultravnc/UltraVNC/issues/129#issuecomment-4233132641
- https://github.com/ultravnc/UltraVNC/issues/129#issuecomment-4236324799

It is normal to have it after your changes of this year about cursor (1.7.x and 1.8.x builds)?

A big improvement has been done but can you read the comments?

**Comment by mikemeinz** [comment]
I will add that I am using UltraVNC daily and I am pleased with the results. I have no complaints at this time. My comments were reporting my experiences but I am not lobbying for another patch. Thank You for your work on UltraVNC.

**Comment by Neustradamus** [comment]
@mikemeinz: Thanks :)

Your comments are important about the size of the cursors...

**Comment by tp01-gogogo** [comment]
Thanks for all the works!

**Comment by Neustradamus** [comment]
@tp01-gogogo: Several years after, you are here!

Have you tried the latest 1.8.x branch version?
- https://forum.uvnc.com/viewtopic.php?t=38158

What do you think about @mikemeinz remarks?

**Comment by Neustradamus** [comment]
@tp01-gogogo: Several years after, you are here!

Have you tried the latest 1.8.x branch version?
- https://forum.uvnc.com/viewtopic.php?t=38158

What do you think about @mikemeinz remarks?

**Comment by Neustradamus** [comment]
@tp01-gogogo: Several years after, you are here!

What do you think about @mikemeinz remarks?

Have you tested the latest 1.8.x branch version?
- https://forum.uvnc.com/viewtopic.php?t=38158

It has been solved?
